"""
Compliance Alert DocType Controller.

Stores alerts generated by AI anomaly detection and risk analysis.
"""

import json

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import now_datetime


class ComplianceAlert(Document):
	"""Controller for Compliance Alert DocType."""

	def before_insert(self):
		"""Set detection timestamp."""
		if not self.detected_at:
			self.detected_at = now_datetime()

	def on_update(self):
		"""Handle status changes."""
		if self.has_value_changed("status"):
			if self.status == "Resolved":
				self.resolved_at = now_datetime()
				self.resolved_by = frappe.session.user
				# Use db_set to update specific fields without triggering another save
				frappe.db.set_value(
					"Compliance Alert",
					self.name,
					{"resolved_at": self.resolved_at, "resolved_by": self.resolved_by},
					update_modified=False,
				)

	@staticmethod
	def create_alert(
		alert_type,
		severity,
		title,
		description=None,
		related_doctype=None,
		related_document=None,
		detection_rule=None,
		detection_details=None,
	):
		"""
		Create a new compliance alert.

		Args:
		    alert_type: Type of alert
		    severity: Info, Warning, or Critical
		    title: Alert title
		    description: Detailed description
		    related_doctype: Related DocType
		    related_document: Related document name
		    detection_rule: Rule that triggered alert
		    detection_details: Additional details dict

		Returns:
		    Compliance Alert document
		"""
		alert = frappe.get_doc(
			{
				"doctype": "Compliance Alert",
				"alert_type": alert_type,
				"severity": severity,
				"title": title,
				"description": description,
				"related_doctype": related_doctype,
				"related_document": related_document,
				"detection_rule": detection_rule,
				"detection_details": json.dumps(detection_details) if detection_details else None,
				"status": "New",
			}
		)
		alert.insert(ignore_permissions=True)
		return alert

	@staticmethod
	def get_active_alerts(status=None, severity=None, alert_type=None, limit=50):
		"""
		Get active alerts with optional filters.

		Args:
		    status: Filter by status
		    severity: Filter by severity
		    alert_type: Filter by alert type
		    limit: Maximum alerts to return

		Returns:
		    List of alert documents
		"""
		filters = {}

		if status:
			filters["status"] = status
		else:
			filters["status"] = ["not in", ["Resolved", "Dismissed"]]

		if severity:
			filters["severity"] = severity

		if alert_type:
			filters["alert_type"] = alert_type

		return frappe.get_all(
			"Compliance Alert",
			filters=filters,
			fields=[
				"name",
				"alert_type",
				"severity",
				"status",
				"title",
				"description",
				"detected_at",
				"related_doctype",
				"related_document",
			],
			order_by="detected_at desc",
			limit=limit,
		)

	@staticmethod
	def acknowledge(alert_name):
		"""Acknowledge an alert."""
		frappe.db.set_value("Compliance Alert", alert_name, "status", "Acknowledged")

	@staticmethod
	def resolve(alert_name):
		"""Resolve an alert."""
		alert = frappe.get_doc("Compliance Alert", alert_name)
		alert.status = "Resolved"
		alert.save(ignore_permissions=True)

	@staticmethod
	def dismiss(alert_name):
		"""Dismiss an alert."""
		frappe.db.set_value("Compliance Alert", alert_name, "status", "Dismissed")

	@staticmethod
	def get_alert_counts():
		"""Get counts of alerts by status and severity."""
		counts = {"by_status": {}, "by_severity": {}, "by_type": {}, "total_active": 0}

		# Count by status
		status_counts = frappe.db.sql(
			"""
            SELECT status, COUNT(*) as count
            FROM `tabCompliance Alert`
            GROUP BY status
        """,
			as_dict=True,
		)

		for row in status_counts:
			counts["by_status"][row.status] = row.count
			if row.status not in ("Resolved", "Dismissed"):
				counts["total_active"] += row.count

		# Count by severity (active only)
		severity_counts = frappe.db.sql(
			"""
            SELECT severity, COUNT(*) as count
            FROM `tabCompliance Alert`
            WHERE status NOT IN ('Resolved', 'Dismissed')
            GROUP BY severity
        """,
			as_dict=True,
		)

		for row in severity_counts:
			counts["by_severity"][row.severity] = row.count

		# Count by type (active only)
		type_counts = frappe.db.sql(
			"""
            SELECT alert_type, COUNT(*) as count
            FROM `tabCompliance Alert`
            WHERE status NOT IN ('Resolved', 'Dismissed')
            GROUP BY alert_type
        """,
			as_dict=True,
		)

		for row in type_counts:
			counts["by_type"][row.alert_type] = row.count

		return counts
